Google command improvement & small changes
- add Google apps (as Calendar, Translate) to Google command
- add -v(-f), -i(-g) and -q option in Google command
- add replaceSymbols function for symbols as +, &, % etc. in Google
command
- change in error messages; they are stderr now, not stdout

diff --git a/UNIX/bin/backup b/UNIX/bin/backup
--- a/UNIX/bin/backup
+++ b/UNIX/bin/backup
@@ -66,14 +66,13 @@ if [[ $1 == '-h' || $1 == '-?' || $1 == '--help' ]]; then
 fi
 
 if [[ ! $mounted ]]; then
-	echo; echo "The external drive is not mounted."
-	echo; echo " Try:	backup [-h] [-?] [--help] for help"; echo
+	echo; echo >&2 "The external drive is not mounted."
+	echo; echo >&2 " Try:	backup [-h] [-?] [--help] for help"; echo
 	exit 1
 fi
 
 
 if [[ $1 == '--linux' ]] || (( $# == 0 )); then
-
 	doBackup "$backupDIR"/Linux "$HOME/*" backup.tar.gz
 fi
 
@@ -98,5 +97,5 @@ if [[ $1 == '--windows' || $1 == '-w' ]]; then
 	fi
 fi
 
-echo "An error occurred. Exit code: 2"
+echo >&2 "An error occurred. Exit code: 2"
 exit 2
diff --git a/UNIX/bin/forum b/UNIX/bin/forum
--- a/UNIX/bin/forum
+++ b/UNIX/bin/forum
@@ -19,6 +19,6 @@ elif [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
 	cat ~/bin/.$SCRIPTNAME.help
 	exit
 else
-	echo "An error occurred. Use -h, -? or --help option for help"
+	echo >&2 "An error occurred. Use -h, -? or --help option for help"
 	exit 1
 fi
diff --git a/UNIX/bin/off b/UNIX/bin/off
--- a/UNIX/bin/off
+++ b/UNIX/bin/off
@@ -13,6 +13,6 @@ elif [[ $1 == '-s' || $1 == '--suspend' ]]; then
 elif [[ $1 == '-h' || $1 == '-?' || $1 == '--help' ]]; then
 	cat ~/bin/.$SCRIPTNAME.help
 else
-	echo "Error: argument not recognised. Exit code: 1"
+	echo >&2 "Error: argument not recognised. Exit code: 1"
 	exit 1
 fi
diff --git a/UNIX/bin/windows b/UNIX/bin/windows
--- a/UNIX/bin/windows
+++ b/UNIX/bin/windows
@@ -46,7 +46,7 @@ sudo echo -n
 
 if [[ $option == '-m' ]]; then
 	if [[ $mounted ]]; then
-		echo "Error: Windows is already mounted. Exit code: 2"
+		echo >&2 "Error: Windows is already mounted. Exit code: 2"
 		exit 2
 	fi
 
@@ -61,7 +61,7 @@ fi
 
 if [[ $option == '-u' ]]; then
 	if [[ ! $mounted ]]; then
-		echo "Error: Windows is not mounted. Unable to unmount. Exit code: 3"
+		echo >&2 "Error: Windows is not mounted. Unable to unmount. Exit code: 3"
 		if [[ -d /media/$USER/Windows ]]; then
 			rm -fr /media/$USER/Windows
 		fi
@@ -76,5 +76,5 @@ if [[ $option == '-u' ]]; then
 	exit
 fi
 
-echo "An error occurred. Exit code: 1"
+echo >&2 "An error occurred. Exit code: 1"
 exit 1
