Merge from toCode to master (#22)
* Add pdf files

* Update README.md

* Add simple graph algorithms

* Add topological_sorting.py and euler_cycle.py

* add Millers 15 task - jebany kwestionariusz gdzie o chuj chodzi

* modify gitignore

* add new homework from Miller - not finished

* something with Millers PI

* add ASD10 tasks

* Update compile and memcheck

– add warning flags and debug flag in 'compile'
– update 'memcheck' so it works with .c and .cpp arguments

* Add graph algorithms in .cpp

* Add pdf file with tasks

* add tasks 09 form Miller

* Add exception

* 11th tasks off/ online

* add Miller's 10th tasks

* Add lab08 tasks

* Update BFS.py and DFS.py

* Update README.md

* improve codes

* improve codes

Co-authored-by: tomgar7 <tomgar7@github.com>
Co-authored-by: Szymon Rys <szymon.rys@awesome-ind.com>
Co-authored-by: mrrys00 <rysszymon00@gmail.com>

diff --git a/archive/Sem1/UNIX/bin/memcheck b/archive/Sem1/UNIX/bin/memcheck
--- a/archive/Sem1/UNIX/bin/memcheck
+++ b/archive/Sem1/UNIX/bin/memcheck
@@ -9,16 +9,28 @@ elif [[ $# > 1 ]]; then
 elif [[ ! -f $1 ]]; then
 	echo >&2 "The argument is not a file..."
 	exit 3
-elif [[ ! -x $1 ]]; then
+elif [[ ! -x $1 && `echo $1 | awk -F. '{print $NF}'` == 'out' ]]; then
 	echo >&2 "The file is not executable..."
 	echo "Try: chmod +x $1"
 	exit 4
 fi
 
-FILENAMEWITHOUTEXTENTION=`echo $1 | rev | cut -d. -f 2- | rev`
-LOGFILENAME="$FILENAMEWITHOUTEXTENTION.log"
+EXTENTION=`echo $1 | awk -F. '{print $NF}'`
+if [[ $EXTENTION == 'c' ]]; then
+	compile -c $1
+elif [[ $EXTENSION == 'cpp' ]]; then
+	compile -cpp $1
+elif [[ ! $EXTENTION == 'out' ]]; then
+	echo >&2 "The format is not supported..."
+	exit 5
+fi
+
+FILENAMEWITHOUTEXTENSION=`echo $1 | rev | cut -d. -f 2- | rev`
+LOGFILENAME="$FILENAMEWITHOUTEXTENSION.log"
 LOGDIRECTORY="$HOME/log/valgrind/"
+PROGRAM="$FILENAMEWITHOUTEXTENSION.out"
+
 mkdir -p $LOGDIRECTORY
 LOGFILE="$LOGDIRECTORY/$LOGFILENAME"
 
-valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=$LOGFILE ./$1 && cat $LOGFILE || echo >&2 "An error occurred..."
+valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=$LOGFILE ./$PROGRAM && cat $LOGFILE || echo >&2 "An error occurred..."
